[build]
  command = "npm ci && npm run build"
  publish = "dist"

# JavaScript assets MUST have correct MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# CSS assets
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# SPA fallback - MUST come after static asset rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200